name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test || echo "No tests defined, skipping"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: raheem404
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t raheem404/smart-waste-app:${{ github.sha }} .
          docker tag raheem404/smart-waste-app:${{ github.sha }} raheem404/smart-waste-app:latest
          docker push raheem404/smart-waste-app:${{ github.sha }}
          docker push raheem404/smart-waste-app:latest

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "'"$RENDER_SERVICE_ID"'"}' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys